name: PIMS Regression Automated Tests

# This workflow is responsible for run mvn test on self-hosted java machine using tags and env , generates single file allure HTML report and then share the report via email to all stakeholders.
# Muzammil Hussain

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Maven Tests with Tags
        run: mvn clean test allure:report

      - name: Generate Single File HTML Report
        if: always()
        run: allure generate .\target\allure-results\ --single-file --clean

      - name: Send Email Notification with Report
        if: always()
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: muzammil.hussain@logicielservice.com
          CC_EMAIL: javeria.tabassum@logicielservice.com,kehkashan.aslam@logicielservice.com,muhammad.aeraz@logicielservice.com,muhammad.hassam@logicielservice.com
          ATTACHMENT_PATH: allure-report/index.html
        run: |
          $subject = "Automated PIMS Regression Tests Report"  
          $body = @"  
          Hi Team,  

          I hope this message finds you well.  

          Please find attached the Regression Tests report for the PIMS.  

          The report includes the results of the executed tests and provides insights into the current state of our PIMS. Please review it at your earliest convenience.  

          If you have any questions or need further information, feel free to reach out.  

          Best Regards,  
          QA Team  
          Logiciel.  
          "@  

          # Send the email using PowerShell  
          $smtp = New-Object Net.Mail.SmtpClient($env:SMTP_SERVER, $env:SMTP_PORT)  
          $smtp.EnableSsl = $true  
          $smtp.Credentials = New-Object Net.NetworkCredential($env:SMTP_USER, $env:SMTP_PASSWORD)  

          $mail = New-Object Net.Mail.MailMessage  
          $mail.From = $env:SMTP_USER  
          $mail.To.Add($env:TO_EMAIL)  
          $mail.Cc.Add($env:CC_EMAIL)
          $mail.Subject = $subject  
          $mail.Body = $body  
          $mail.Attachments.Add($env:ATTACHMENT_PATH)  

          $smtp.Send($mail)